// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PcBuilder.DAL.MySQL;

#nullable disable

namespace PcBuilder.DAL.MySQL.Migrations
{
    [DbContext(typeof(BuilderDBContext))]
    [Migration("20240318095937_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BuildComponent", b =>
                {
                    b.Property<Guid>("buildsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("componentsId")
                        .HasColumnType("char(36)");

                    b.HasKey("buildsId", "componentsId");

                    b.HasIndex("componentsId");

                    b.ToTable("BuildComponent");
                });

            modelBuilder.Entity("PcBuilder.DAL.MySQL.Entities.Build", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("builds");
                });

            modelBuilder.Entity("PcBuilder.DAL.MySQL.Entities.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("typeID")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("typeID");

                    b.ToTable("components");
                });

            modelBuilder.Entity("PcBuilder.DAL.MySQL.Entities.ComponentCharact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("componentId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("componentId");

                    b.ToTable("componentCharacts");
                });

            modelBuilder.Entity("PcBuilder.DAL.MySQL.Entities.ComponentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("componentTypes");
                });

            modelBuilder.Entity("BuildComponent", b =>
                {
                    b.HasOne("PcBuilder.DAL.MySQL.Entities.Build", null)
                        .WithMany()
                        .HasForeignKey("buildsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PcBuilder.DAL.MySQL.Entities.Component", null)
                        .WithMany()
                        .HasForeignKey("componentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcBuilder.DAL.MySQL.Entities.Component", b =>
                {
                    b.HasOne("PcBuilder.DAL.MySQL.Entities.ComponentType", "type")
                        .WithMany("components")
                        .HasForeignKey("typeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("type");
                });

            modelBuilder.Entity("PcBuilder.DAL.MySQL.Entities.ComponentCharact", b =>
                {
                    b.HasOne("PcBuilder.DAL.MySQL.Entities.Component", "component")
                        .WithMany("characts")
                        .HasForeignKey("componentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("component");
                });

            modelBuilder.Entity("PcBuilder.DAL.MySQL.Entities.Component", b =>
                {
                    b.Navigation("characts");
                });

            modelBuilder.Entity("PcBuilder.DAL.MySQL.Entities.ComponentType", b =>
                {
                    b.Navigation("components");
                });
#pragma warning restore 612, 618
        }
    }
}
